# .github/workflows/generate-posts.yml

name: Generate Posts List

# This action will trigger on pushes to the 'experiment' branch,
# but ONLY if changes were made in the 'posts/' directory.
on:
  push:
    branches:
        - experiment
    paths:
      - 'posts/**'

# A job to run our script
jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    # Set permissions for the job to allow it to write to the repository
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a recent, stable version of Node.js

      # Step 3: Run the post generator script
      # This will modify the posts.json file in the workflow's workspace
      - name: Run Post Generator
        run: node generate-posts-list.js

      # Step 4: Use a pre-built action to automatically commit and push the changes
      # This action checks if there are any changes and only commits if posts.json was modified.
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Auto-generate posts.json'
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>